version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh #nginx 연결되지 않은 서버 종료
      time: 60
      runas: ec2-user
  ApplicationsStart:
    - location: start.sh #nginx 연결되지 않은 port로 세 버전의 서버 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh #nginx 새 서버가 정상적인지 확인
      timeout: 60
      runas: ec2-user